language: node_js
node_js:
  - "8"
install:
  - npm install
script:
  - mv src/app/firebase.config.example.ts src/app/firebase.config.ts
  - npm run build
  - npm run build:docs
  - npm run build:electron
  - npm run build:electron:main
